In [ ]:
# 이승율(2023202417)

In [ ]:
# Week11

In [ ]:
# How to import NumPy

In [1]:
import numpy as np

In [ ]:
# Reading the example code

In [2]:
a = np.arange(6)
type(a)

numpy.ndarray

In [3]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [ ]:
# What is an array?

In [4]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
print(a[0])

[1 2 3 4]


In [7]:
print(a[1])

[5 6 7 8]


In [8]:
# More information about arrays
# What are the attributes of an array?

a = np.array([[0.,0.,0.],
              [1.,1.,1.]])
a

array([[0., 0., 0.],
       [1., 1., 1.]])

In [9]:
# How to create a basic array

a = np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
np.zeros(2)

array([0., 0.])

In [11]:
np.ones(2)

array([1., 1.])

In [12]:
np.empty(2)

array([1., 1.])

In [13]:
np.arange(4)

array([0, 1, 2, 3])

In [14]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [15]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [16]:
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [17]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [18]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [20]:
# Adding, removing, and sorting elements

In [21]:
arr = np.array([2,1,5,3,7,4,6,8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [22]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
# How do you know the shape and size of an array?

In [26]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example.ndim

3

In [27]:
array_example.size

24

In [28]:
array_example.shape

(3, 2, 4)

In [29]:
# Can you reshape an array?

In [30]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [31]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [32]:
np.reshape(a, newshape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [33]:
# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [34]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [35]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [36]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [37]:
a

array([1, 2, 3, 4, 5, 6])

In [38]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [39]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [40]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [41]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [42]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [43]:
a

array([1, 2, 3, 4, 5, 6])

In [44]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [45]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [46]:
a

array([1, 2, 3, 4, 5, 6])

In [47]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [48]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [49]:
c

array([[1, 2, 3, 4, 5, 6]])

In [50]:
# Indexing and slicing

In [51]:
data = np.array([1,2,3])

In [52]:
data[1]

2

In [53]:
data[0:2]

array([1, 2])

In [54]:
data[1:]

array([2, 3])

In [55]:
data[-2:]

array([2, 3])

In [57]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [58]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
print(a[a<5])

[1 2 3 4]


In [60]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [61]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [62]:
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [63]:
c = a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [64]:
five_up = (a>5) | (a==5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [65]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [67]:
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [68]:
print(a[b])

[1 2 3 4]


In [69]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [70]:
# How to create an array from existing data

In [71]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [72]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [76]:
a1 = np.array([[1,1],
               [2,2]])

a2 = np.array([[3,3],
               [4,4]])

print(a1)
print(a2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [77]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [78]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [80]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [81]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [82]:
np.hsplit(x, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [83]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [85]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [86]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
# Basic array operations

In [90]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)
data+ones

array([2, 3])

In [91]:
data-ones

array([0, 1])

In [92]:
data*ones

array([1, 2])

In [93]:
data*data

array([1, 4])

In [94]:
data/data

array([1., 1.])

In [95]:
ones-ones

array([0, 0])

In [96]:
ones/ones

array([1., 1.])

In [97]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [98]:
a.sum()

10

In [99]:
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [100]:
b.sum(axis=0)

array([3, 3])

In [101]:
b

array([[1, 1],
       [2, 2]])

In [102]:
b.sum(axis=1)

array([2, 4])

In [103]:
b

array([[1, 1],
       [2, 2]])

In [104]:
# Broadcasting

In [105]:
data = np.array([1.0, 2.0])
data

array([1., 2.])

In [106]:
data*1.6

array([1.6, 3.2])

In [107]:
# More useful array operations

In [108]:
data.max()

2.0

In [109]:
data.min()

1.0

In [110]:
data.sum()

3.0

In [111]:
data.mean()

1.5

In [112]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [113]:
a.sum()

4.8595784

In [114]:
a.min()

0.05093587

In [115]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [116]:
a.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [117]:
# Creating matrices

In [118]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
data[0.1]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [120]:
data[0.1]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [121]:
data[0,1]

2

In [122]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [123]:
data[0:2, 0]

array([1, 3])

In [124]:
data.max()

6

In [125]:
data.min()

1

In [126]:
data.sum()

21

In [127]:
data.mean()

3.5

In [128]:
data = np.array([[1,2],[5,3],[4,6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [129]:
data.max(axis=0)

array([5, 6])

In [130]:
data.max(axis=1)

array([2, 5, 6])

In [131]:
data.min(axis=0)

array([1, 2])

In [132]:
data.min(axis=1)

array([1, 3, 4])

In [133]:
data = np.array([[1,2],[3,4]])
ones = np.array([[1,1],[1,1]])
data+ones

array([[2, 3],
       [4, 5]])

In [134]:
data*ones

array([[1, 2],
       [3, 4]])

In [135]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [138]:
ones_row = np.array([[1,1]])
ones_row

array([[1, 1]])

In [139]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [141]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [142]:
np.ones(3)

array([1., 1., 1.])

In [143]:
np.zeros(3)

array([0., 0., 0.])

In [144]:
rng = np.random.default_rng()
rng.random(3)

array([0.7890471 , 0.6379058 , 0.93704119])

In [145]:
np.random.random(5)

array([0.79258015, 0.56160599, 0.68944317, 0.31602379, 0.20354962])

In [146]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [147]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [148]:
rng.random((3,2))

array([[0.77514255, 0.56306175],
       [0.18628899, 0.39965956],
       [0.82526379, 0.5720281 ]])

In [150]:
# Generating random numbers

In [151]:
rng.integers(5, size=(2,4))

array([[1, 3, 4, 4],
       [1, 1, 2, 0]], dtype=int64)

In [152]:
# How to get unique items and counts

In [153]:
a = np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,19,20])
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [154]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [155]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [156]:
return_counts, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [157]:
a_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]])

In [158]:
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [159]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [160]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [161]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [162]:
print(indices)

[0 1 2]


In [163]:
print(occurrence_count)

[2 1 1]


In [164]:
# Transposing and reshaping a matrix

In [165]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [166]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [167]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [169]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [170]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [171]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [172]:
# How to reverse an array

In [173]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [174]:
reversed_arr = np.flip(arr)

In [175]:
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [176]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [177]:
reversed_arr = np.flip(arr_2d)
reversed_arr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [178]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
reversed_arr_rows

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [179]:
reversed_arr_cols = np.flip(arr_2d, axis=1)
reversed_arr_cols

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [180]:
arr_2d[1] = np.flip(arr_2d[1])
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [181]:
arr_2d[0] = np.flip(arr_2d[1])

In [182]:
arr_2d

array([[ 5,  6,  7,  8],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [183]:
arr_2d[0] = np.flip(arr_2d[0])
arr_2d

array([[ 8,  7,  6,  5],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [184]:
arr_2d[0] = ([1,2,3,4])

In [185]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [186]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
arr_2d

array([[ 1, 10,  3,  4],
       [ 8,  7,  6,  5],
       [ 9,  2, 11, 12]])

In [187]:
# Reshaping and flattening multidimensional arrays

In [188]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [189]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [191]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [192]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [193]:
a2 = x.ravel()

In [194]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [195]:
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [196]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# End